[DataServerInfo]
;==================================================
; Customer Settings
;==================================================
CustomerLicenseId = MuOnline

;==================================================
; Database Settings
;==================================================
DataServerODBC = MuOnline97
DataServerPort = 55960