-- ============================================================================
-- SCRIPT DE CRIACAO AUTOMATICA DE 50 CONTAS E PERSONAGENS LEVEL 2 (+11 EXATOS)
-- Banco de Dados: MuOnline97 / MuOnline (SSeMU 97k)
-- Data de Criacao: 16/08/2026
--
-- EXPLICACAO E RECURSOS:
-- 1. Classes Level 2 ativadas: Blade Knight (17), Soul Master (1), Muse Elf (33), Magic Gladiator (48).
-- 2. Blade Knight: Knight Blade + Chaos Shield + Dragon Set +11.
-- 3. Soul Master: Legendary Staff + Legendary Shield + Legendary Set +11.
-- 4. Muse Elf: Celestial Bow + Divine Set +11.
-- 5. Magic Gladiator: Absolute Staff of Archangel + Legendary Shield + Hurricane Set +11.
-- 6. Opcoes +11 Exatas: Sets/Shields/Rings/Pendants (Luck+Opt28+Reflect+Diminui), Armas (Skill+Luck+Opt28+Dano2%+Rate10%).
-- ============================================================================

USE [MuOnline97]
GO

SET NOCOUNT ON; -- Oculta contadores de linhas afetadas para execucao rapida

-- Garante que a coluna Inventory da tabela Character suporte o tamanho do inventario
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Character' AND COLUMN_NAME = 'Inventory' AND CHARACTER_MAXIMUM_LENGTH < 1728)
BEGIN
    ALTER TABLE [dbo].[Character] ALTER COLUMN [Inventory] VARBINARY(1728);
END
GO

-- Definicao das cadeias de bytes hexadecimais do inventario equipado para cada classe
DECLARE @DW_INV VARBINARY(1728) = 0xA5DFFF00000000680000000000000000CEDFFF000000004C0000000000000000E35FFF000000004C0000000000000000035FFF00000000CC0000000000000000235FFF00000000CC0000000000000000435FFF00000000CC0000000000000000635FFF00000000CC000000000000000084DFFF00000000C20000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAC5FFF00000000CC0000000000000000A85FFF00000000CC0000000000000000A95FFF00000000CC0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;   -- Soul Master (Legendary Staff+Shield+Set + Asa 2 + Pendant + 2x Rings +11)
DECLARE @DK_INV VARBINARY(1728) = 0x13DFFF00000000680000000000000000CDDFFF000000004C0000000000000000E15FFF000000004C0000000000000000015FFF00000000CC0000000000000000215FFF00000000CC0000000000000000415FFF00000000CC0000000000000000615FFF00000000CC000000000000000085DFFF00000000C20000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAC5FFF00000000CC0000000000000000A85FFF00000000CC0000000000000000A95FFF00000000CC0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;   -- Blade Knight (Knight Blade + Chaos Shield + Dragon Set + Asa 2 + Pendant + 2x Rings +11)
DECLARE @ELF_INV VARBINARY(1728) = 0x92DFFF00000000680000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEA5FFF000000004C00000000000000000A5FFF00000000CC00000000000000002A5FFF00000000CC00000000000000004A5FFF00000000CC00000000000000006A5FFF00000000CC000000000000000083DFFF00000000C20000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAD5FFF00000000CC0000000000000000A85FFF00000000CC0000000000000000A95FFF00000000CC0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF; -- Muse Elf (Celestial Bow + Divine Set + Asa 2 + Pendant + 2x Rings +11)
DECLARE @MG_INV VARBINARY(1728) = 0xAADFFF00000000680000000000000000CEDFFF000000004C0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0F5FFF00000000CC00000000000000002F5FFF00000000CC00000000000000004F5FFF00000000CC00000000000000006F5FFF00000000CC000000000000000086DFFF00000000C20000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAC5FFF00000000CC0000000000000000A85FFF00000000CC0000000000000000A95FFF00000000CC0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;   -- Magic Gladiator (Absolute Staff of Archangel + Legendary Shield + Hurricane Set +11)

-- Tabela temporaria em memoria para exibir o relatorio detalhado final
DECLARE @ContasCriadas TABLE (
    Num INT,               -- Numero da conta (1 a 50)
    Login VARCHAR(10),     -- Nome do usuario (memb___id)
    Senha VARCHAR(10),     -- Senha de acesso (123456)
    NickName VARCHAR(10),  -- Nome do personagem criado
    Classe VARCHAR(20),    -- Nome da classe (Soul Master, Blade Knight, etc.)
    SetEquipado VARCHAR(80)-- Descricao dos itens equipados no personagem
);

-- Tabela temporaria contendo a lista de 50 Nicknames RPG unicos (max 10 caracteres)
DECLARE @Nicks TABLE (Id INT IDENTITY(1,1), Nick VARCHAR(10));
INSERT INTO @Nicks (Nick) VALUES ('Ares97'); -- Registra o nickname 'Ares97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('ViperX'); -- Registra o nickname 'ViperX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Zeus97'); -- Registra o nickname 'Zeus97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('PredatorX'); -- Registra o nickname 'PredatorX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('ShadowK'); -- Registra o nickname 'ShadowK' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Kratos97'); -- Registra o nickname 'Kratos97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('TitanX'); -- Registra o nickname 'TitanX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Apollo97'); -- Registra o nickname 'Apollo97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('RagnarX'); -- Registra o nickname 'RagnarX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Odin97'); -- Registra o nickname 'Odin97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('ThorX'); -- Registra o nickname 'ThorX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Hulk97'); -- Registra o nickname 'Hulk97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('VenomX'); -- Registra o nickname 'VenomX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Ghost97'); -- Registra o nickname 'Ghost97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('PhoenixX'); -- Registra o nickname 'PhoenixX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Blade97'); -- Registra o nickname 'Blade97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('DragonX'); -- Registra o nickname 'DragonX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Slayer97'); -- Registra o nickname 'Slayer97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('NexusX'); -- Registra o nickname 'NexusX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Vortex97'); -- Registra o nickname 'Vortex97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('HunterX'); -- Registra o nickname 'HunterX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Storm97'); -- Registra o nickname 'Storm97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('ZeroX'); -- Registra o nickname 'ZeroX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Hyper97'); -- Registra o nickname 'Hyper97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('AlphaX'); -- Registra o nickname 'AlphaX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Omega97'); -- Registra o nickname 'Omega97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('VectorX'); -- Registra o nickname 'VectorX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Apex97'); -- Registra o nickname 'Apex97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('MatrixX'); -- Registra o nickname 'MatrixX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Cyber97'); -- Registra o nickname 'Cyber97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('SonicX'); -- Registra o nickname 'SonicX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Nitro97'); -- Registra o nickname 'Nitro97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('BlazeX'); -- Registra o nickname 'BlazeX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Inferno97'); -- Registra o nickname 'Inferno97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('FrostX'); -- Registra o nickname 'FrostX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Blizzard97'); -- Registra o nickname 'Blizzard97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('ThunderX'); -- Registra o nickname 'ThunderX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Light97'); -- Registra o nickname 'Light97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('StarlightX'); -- Registra o nickname 'StarlightX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Comet97'); -- Registra o nickname 'Comet97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('NovaX'); -- Registra o nickname 'NovaX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Eclipse97'); -- Registra o nickname 'Eclipse97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('SolarX'); -- Registra o nickname 'SolarX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Lunar97'); -- Registra o nickname 'Lunar97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('CosmosX'); -- Registra o nickname 'CosmosX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Galaxy97'); -- Registra o nickname 'Galaxy97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('OrbitX'); -- Registra o nickname 'OrbitX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Pulsar97'); -- Registra o nickname 'Pulsar97' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('ZenithX'); -- Registra o nickname 'ZenithX' na tabela auxiliar
INSERT INTO @Nicks (Nick) VALUES ('Valkyrie97'); -- Registra o nickname 'Valkyrie97' na tabela auxiliar

-- Declaracao das variaveis de controle da iteracao
DECLARE @i INT = 1;                              -- Contador do laco WHILE (inicia em 1)
DECLARE @AccountID VARCHAR(10);                  -- Armazena o login gerado (ex: test01)
DECLARE @CharName VARCHAR(10);                   -- Armazena o nickname do personagem
DECLARE @Password VARCHAR(10) = '123456';        -- Senha padrao para todas as contas
DECLARE @Class TINYINT;                          -- Codigo numerico da Classe (1=SM, 17=BK, 33=ME, 48=MG)
DECLARE @ClassName VARCHAR(20);                  -- Nome legivel da Classe
DECLARE @SetDesc VARCHAR(80);                    -- Descricao do kit de itens da classe
DECLARE @Inventory VARBINARY(1728);              -- Buffer binario do inventario equipado

-- Inicio do laco para criar as 50 contas e personagens
WHILE @i <= 50
BEGIN
    -- Formata o nome de login limpo com 2 digitos (test01 ate test50)
    SET @AccountID = 'test' + RIGHT('0' + CAST(@i AS VARCHAR(2)), 2);
    
    -- Seleciona o nickname correspondente na tabela auxiliar de nicks
    SELECT @CharName = Nick FROM @Nicks WHERE Id = @i;
    IF @CharName IS NULL SET @CharName = 'Player' + RIGHT('0' + CAST(@i AS VARCHAR(2)), 2);

    -- ------------------------------------------------------------------------
    -- LOGICA DE ALTERNANCIA DE CLASSES LEVEL 2 E INVENTARIOS HASH
    -- Utiliza o operador de resto da divisao (@i % 4) para alternar entre as 4 classes
    -- ------------------------------------------------------------------------
    IF (@i % 4 = 1) BEGIN
        SET @Class = 17;                                                               -- 17 = Blade Knight (Classe Lvl 2)
        SET @ClassName = 'Blade Knight';                                               -- Nome de exibicao da classe
        SET @SetDesc = 'Knight Blade + Chaos Shield + Dragon Set +11 (Luck+Opt28+Full)'; -- Descricao
        SET @Inventory = @DK_INV;                                                      -- Aloca os bytes hexadecimais do BK
    END ELSE IF (@i % 4 = 2) BEGIN
        SET @Class = 1;                                                                -- 1 = Soul Master (Classe Lvl 2)
        SET @ClassName = 'Soul Master';                                                -- Nome de exibicao da classe
        SET @SetDesc = 'Legendary Staff + Shield + Legendary Set +11 (Luck+Opt28+Full)';-- Descricao
        SET @Inventory = @DW_INV;                                                      -- Aloca os bytes hexadecimais do SM
    END ELSE IF (@i % 4 = 3) BEGIN
        SET @Class = 33;                                                               -- 33 = Muse Elf (Classe Lvl 2)
        SET @ClassName = 'Muse Elf';                                                   -- Nome de exibicao da classe
        SET @SetDesc = 'Celestial Bow + Divine Set +11 (Luck+Opt28+Full)';             -- Descricao
        SET @Inventory = @ELF_INV;                                                     -- Aloca os bytes hexadecimais da ME
    END ELSE BEGIN
        SET @Class = 48;                                                               -- 48 = Magic Gladiator (MG)
        SET @ClassName = 'Magic Gladiator';                                            -- Nome de exibicao da classe
        SET @SetDesc = 'Absolute Staff Archangel + Legendary Shield + Hurricane Set +11'; -- Descricao
        SET @Inventory = @MG_INV;                                                      -- Aloca os bytes hexadecimais do MG
    END

    -- ------------------------------------------------------------------------
    -- 1. CRIACAO DA CONTA NA TABELA MEMB_INFO
    -- Registra o login, senha e configuracoes universais de acesso
    -- ------------------------------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM [dbo].[MEMB_INFO] WHERE memb___id = @AccountID) BEGIN
        INSERT INTO [dbo].[MEMB_INFO] (
            [memb___id], [memb__pwd], [memb_name], [sno__numb],
            [bloc_code], [ctl1_code], [AccountLevel], [AccountExpireDate]
        ) VALUES (
            @AccountID, @Password, @AccountID, '111111111111111111',
            '0', '0', 0, '2050-01-01 00:00:00'
        );
    END

    -- ------------------------------------------------------------------------
    -- 2. VINCULO DO PERSONAGEM NA TABELA AccountCharacter
    -- Registra o personagem @CharName no Slot 1 (GameID1) e selecionado (GameIDC)
    -- ------------------------------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM [dbo].[AccountCharacter] WHERE Id = @AccountID) BEGIN
        INSERT INTO [dbo].[AccountCharacter] (
            [Id], [GameID1], [GameIDC], [MoveCnt], [ExtClass], [Locked]
        ) VALUES (
            @AccountID, @CharName, @CharName, 0, 2, 0
        );
    END ELSE BEGIN
        UPDATE [dbo].[AccountCharacter] SET GameID1 = @CharName, GameIDC = @CharName WHERE Id = @AccountID;
    END

    -- ------------------------------------------------------------------------
    -- 3. CRIACAO COMPLETA DO PERSONAGEM NA TABELA Character
    -- Insere nivel 350, 10 resets, status de atributos, Zen e inventario equipado
    -- ------------------------------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM [dbo].[Character] WHERE Name = @CharName) BEGIN
        INSERT INTO [dbo].[Character] (
            [AccountID],        -- ID da conta a qual o personagem pertence
            [Name],             -- Nickname do personagem (unico)
            [cLevel],           -- Nivel do personagem (350)
            [LevelUpPoint],     -- Pontos nao distribuidos livres (5.000)
            [Class],            -- Codigo da classe (1=SM, 17=BK, 33=ME, 48=MG)
            [Experience],       -- Pontos de experiencia acumulados (100.000.000)
            [Strength],         -- Atributo de Forca (1.000)
            [Dexterity],        -- Atributo de Agilidade (1.000)
            [Vitality],         -- Atributo de Vitalidade (1.000)
            [Energy],           -- Atributo de Energia (1.000)
            [Inventory],        -- Estrutura binaria do inventario com itens +11
            [Money],            -- Quantidade de Zen no inventario (100.000.000)
            [Life], [MaxLife],  -- Vida Atual e Vida Maxima (1.000 / 1.000)
            [Mana], [MaxMana],  -- Mana Atual e Mana Maxima (1.000 / 1.000)
            [BP], [MaxBP],      -- Stamina/AG Atual e Maxima (500 / 500)
            [MapNumber],        -- Numero do Mapa inicial (0 = Lorencia)
            [MapPosX],          -- Coordenada X inicial no mapa (125)
            [MapPosY],          -- Coordenada Y inicial no mapa (125)
            [MapDir],           -- Direcao inicial de visao do personagem (0)
            [PkCount],          -- Contador de assassinatos/Kills (0)
            [PkLevel],          -- Nivel de PK (3 = Status Amarelo / Normal)
            [PkTime],           -- Tempo restante de penalidade de PK (0)
            [CtlCode],          -- Codigo de Controle do Personagem (0 = Normal, 8 = GM)
            [DbVersion],        -- Versao da estrutura da base de dados (3)
            [ChatLimitTime],    -- Tempo de limite de mute do chat (0)
            [FruitPoint],       -- Pontos de frutos adicionados (0)
            [FruitAddPoint],    -- Pontos adicionais de frutas (0)
            [FruitSubPoint],    -- Pontos subtraidos de frutas (0)
            [ResetCount],       -- Quantidade de resets do personagem (10 Resets)
            [MasterResetCount], -- Quantidade de Master Resets (0)
            [IsNewChar]         -- Indicador de personagem recem-criado (0)
        ) VALUES (
            @AccountID, @CharName, 350, 5000, @Class, 100000000,
            1000, 1000, 1000, 1000,
            @Inventory, 100000000, 1000, 1000, 1000, 1000, 500, 500,
            0, 125, 125, 0, 0, 3, 0,
            0, 3, 0, 0, 0, 0,
            10, 0, 0
        );
    END

    -- Armazena os dados gerados na tabela temporaria do relatorio
    INSERT INTO @ContasCriadas (Num, Login, Senha, NickName, Classe, SetEquipado)
    VALUES (@i, @AccountID, @Password, @CharName, @ClassName, @SetDesc);

    -- Incrementa a variavel contadora do loop WHILE
    SET @i = @i + 1;
END

-- ----------------------------------------------------------------------------
-- EXIBICAO DO RELATORIO FINAL DETALHADO NO SQL SERVER MANAGEMENT STUDIO
-- ----------------------------------------------------------------------------
SELECT 
    Num AS [#], 
    Login AS [Login], 
    Senha AS [Senha], 
    NickName AS [Nick], 
    Classe AS [Classe (Lvl 2)], 
    SetEquipado AS [Itens Equipados (+11)] 
FROM @ContasCriadas;

-- Mensagem de confirmacao no console
PRINT '50 Contas e Personagens Lvl 2 com itens +11 configurados com sucesso!';
GO
